### ISSUE TITLE
Swift 1.2 Update

### ISSUE THREAD

**Issue by algera** [jianyaoang/UIColor-Swift-Extension#1]
# Swift 1.2 syntax update

Line 184
if countElements(hexColorString) != 6 {

To
if count(hexColorString) != 6 {
# Documentation consideration

An abbreviated example within the documentation, e.g.:
UIColor().fieryOrange(self.view) // Changes the background of the current view to the fiery orange gradient color

**Comment by jianyaoang** [comment]
Thank you jeffalgera for informing me about the swift update and the documentation suggestion. I've made the changes to update the code, and also updated the documentation for a better explanation.

Thank you again!
